mod antis;
pub mod cached;
mod columns;
pub mod consecutive;
pub mod cumulative;
mod diagonals;
mod direction;
pub mod heuristic;
mod line;
mod lines;
pub mod null;
mod rows;
pub mod termination;
pub mod win;
pub mod wins;

pub use cached::*;
pub use consecutive::*;
pub use cumulative::*;
pub use heuristic::*;
pub use null::*;
pub use win::*;
