[package]
name = "rustep"
version = "0.3.0"
authors = ["artfuldev<hello@artful.dev>"]
edition = "2021"

[dependencies]
anyhow = "1.0.89"
memoize = "0.4.2"
nom = "7.1.3"
num = "0.4.3"
rand = "0.8.5"

[dev-dependencies]
pretty_assertions = "1.4.1"
